repos:
- repo: local
  hooks:
    - id: flask8
      name: flask8
      description: "flask8"
      entry: flask8 --config setup.cfg
      verbose: true
      language: python
      language_version: python3
      types: [python]
