repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      description: "flake8"
      entry: flake8 --config setup.cfg
      verbose: true
      language: python
      language_version: python3
      types: [python]
