 version: 2.1
 executors:
   test-environment:  
     docker:
       - image: circleci/python:3.6.2-stretch
         environment:
           TEST_DATABASE_URL: postgresql://root@127.0.0.1:5432/circle_test
       - image: circleci/postgres:9.6.5-alpine-ram
         environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
   production-environment:
     docker:
       - image: buildpack-deps:trusty
 
 jobs:
   prepare-environment:
     executor: test-environment
     steps:
       - checkout 
       - run:
           command: |
             sudo chown -R circleci:circleci /usr/local/bin
             sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
       - run:
           command: |
             #python3.6 -m venv venv
             sudo apt-get update
             sudo apt-get install -y postgresql-client-9.6
             psql -d $TEST_DATABASE_URL -c 'create database taiga;' -U root
       - restore_cache:
           key: taiga-back-{{ checksum "requirements.txt" }}
       - run: 
           command: |
             #sudo pip install pipenv
             #pipenv install -r requirements.txt
             #pipenv install -r requirements-devel.txt
             pwd
             pwd
             pwd
             pip install -r rrequirements.txt
             ls -al
             pwd
       - save_cache:
           key: taiga-back-{{ checksum "requirements.txt" }}
           paths:
             - "/usr/local/lib/python3.6/site-packages"
             - "/usr/local/bin"
   code-quality:
     executor: test-environment
     steps:
       - checkout
       - run:
           command: |
             sudo chown -R circleci:circleci /usr/local/bin
             sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
       - restore_cache:
           key: taiga-back-{{ checksum "requirements.txt" }}
       - run: 
           name: run unit tests
           command: |
             flake8 --config setup.cfg --format junit-xml --tee --output-file=TEST_FLAKE8_JUNIT.xml
       - store_test_results:
           path: TEST_FLAKE8_JUNIT.xml
       - store_artifacts:
           path: TEST_FLAKE8_JUNIT.xml
   unit-test:
     executor: test-environment
     steps:
       - checkout
       - run:
           command: |
             sudo chown -R circleci:circleci /usr/local/bin
             sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
       - restore_cache:
           key: taiga-back-{{ checksum "requirements.txt" }}
       - run: 
           name: run unit tests
           command: |
             coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' -m pytest -v --tb=native --junitxml TEST_PYTEST_UNIT.xml --disable-pytest-warnings tests/unit
             ls -al
       - store_test_results:
           path: TEST_PYTEST_UNIT.xml
       - store_artifacts:
           path: TEST_PYTEST_UNIT.xml
   integration-test:
     executor: test-environment
     steps:
       - checkout
       - run:
           command: |
             sudo chown -R circleci:circleci /usr/local/bin
             sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
       - restore_cache:
           key: taiga-back-{{ checksum "requirements.txt" }}
       - run: 
           name: run integration tests
           command: |
             coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' -m pytest -v --tb=native --disable-pytest-warnings tests/integration
   
   deploy:
     executor: production-environment
     steps:
       - checkout
       - run:
           name: deploy to master
           command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

 workflows:
   version: 2.1
   build-deploy:
     jobs:
       - prepare-environment
       - code-quality:
           requires:
             - prepare-environment
       - unit-test:
           requires:
             - code-quality
       - integration-test:
           requires:
             - unit-test
       - deploy:
           requires:
             - integration-test
           
